### ISSUE TITLE
Parse fails for contest 1130

### ISSUE THREAD

**Issue by kalpaj12** [johnathan79717/codeforces-parser#16]
This parser doesn't fetch details of question D1 and D2 of codeforces contest 1130.

**Comment by smilitude** [comment]
This happened again for https://codeforces.com/contest/1301. Now we have two pending pull requests for the same issue:  
- https://github.com/johnathan79717/codeforces-parser/pull/18
- https://github.com/johnathan79717/codeforces-parser/pull/17

**Comment by johnathan79717** [comment]
Merged #18 
Thank you @kalpaj12 @smilitude

**Comment by kalpaj12** [comment]
Thanks @johnathan79717 ! :)
