### ISSUE TITLE
Considering separate out input/output generation from code template generation

### ISSUE THREAD

**Issue by pathikrit** [johnathan79717/codeforces-parser#3]
Thank you for developing this! I have a suggestion:

Many codeforces users use other languages like Java, Python and Ruby. They don't really care about care about C/C++. Many users who use C or C++ have their own setup mechanisms. Additionally in languages like Java and Scala, you cannot have class or filenames starting with a number.

It is best to separate this into 2 concerns. Something like `download-tests.py` to simply download the input/output files and `setup-template.py` to setup code template. I think most users of this really like the ability to download the test cases easily.

**Comment by johnathan79717** [comment]
Hi pathikrit,
Thanks for your suggestion.
I don't have much time to implement this. Anyone interested is welcome to send pull requests.

**Comment by brunojadami** [comment]
Hi, right now it copies the template file to the problems folder. You can change the template file macro in line 20 (adding your own template file and extension). Is that enough for your purposes? (Will close the issue, if you have any comments please reopen it ;)).
