### ISSUE TITLE
Python 3 doesn't find problems

### ISSUE THREAD

**Issue by jakobkogler** [johnathan79717/codeforces-parser#5]
Calling the script with Python 3.5 ends in `Found 0 problems!`. 

It finds the correct contest name though.

**Comment by brunojadami** [comment]
Fixed, please try again ;)

**Comment by jakobkogler** [comment]
Yes, thanks. It works fine now. 

Btw. on my system (Manjaro) I had to install `time`(!!!). The time command worked, but `which time` in your test-script returned an error. It couldn't find the location of `time`. After installing it, it returns `/usr/bin/time` like it should.
