### ISSUE TITLE
Support for other languages (Go, Rust)

### ISSUE THREAD

**Issue by MatthiasKauer** [johnathan79717/codeforces-parser#8]
Hi,
I'm interested in adding support for additional languages. This should just require changing the build executable. Since these languages evolve fast, I'd maybe add a version check as well.

Are you interested in merging something like that?
If so, my main question is what the interface should look like. I'd leave C++ as a default. Then we could activate another language from the test.sh script via CLI switch, say "-l go", or "-l rust". Or we create an environment variable, say CODEFORCES_PARSER_LANG to achieve a similar behavior.
What do you think?

Best,
Matthias

**Comment by johnathan79717** [comment]
That's a good idea. I'll be happy to merge that.

**Comment by MatthiasKauer** [comment]
Ok, I've started with this and have some thoughts.
It looks way more easy to integrate extra languages into "parse.py" rather than "test.sh" and I think I'll go that way.

Downside: All 5 problems will necessarily have the same language.

I'll probably add a suffix, so you have 785-cpp and 785-go directories if you want to switch between them.
Not quite what I initially imagined, but still better than nothing, right?
